# This is a basic workflow to help you get started with Actions

name: Master Branch Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  semversioner-prepare-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # We need to get all commits here to determine which log messages
      # to create semversioner change entries for because
      # the most recent one or two might be related to merges or automation
      # actions.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # Runs a set of commands using the runners shell
      - name: Install semversioner and dependencies
        run: |
          python3 --version
          pip3 install semversioner
          pip3 install -r ${{ github.workspace}}/.github/scripts/python/requirements.txt

      # Determines change status for each commit.
      # Will remove dupes and filter list for unwanted comments.
      # Does basic parsing of message text to determine if
      # Creates a .semversioner/next-release folder with hashes for each change
      - name: Prepare Release
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch $CURRENT_BRANCH"
          echo "Pull request from: ${{ github.head_ref }}"
          echo "Pull request to: ${{ github.base_ref }}"
          python3 ${{ github.workspace}}/.github/scripts/python/semversioner_prepare_release.py --head-ref "${{ github.head_ref }}" -d
          git pull && git add .semversioner/*
          #cat .semversioner/next-release/*
          semversioner status


      - name: Show info
        run: |
          git version
          git fetch && git status
          echo "github.ref is: ${{ github.ref }}"
          CURRENT_VERSION=$(semversioner current-version)
          echo "Current version: $CURRENT_VERSION"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          tags: true
